baseURL = "https://crafthippie.github.io/boergers/"
languageCode = "en-us"
title = "Boergers"
disableKinds = ["taxonomy", "RSS", "sitemap"]

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Thomas Boerger"
  description = "Documentation for Minecraft pack Boergers"
  keywords = "minecraft, mod, modpack, forge"
