---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: minecraft-server
    options:
      labels:
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/component: server
    literals:
      - MINECRAFT_MOTD=Boergers by Webhippie

secretGenerator:
  - name: minecraft-server
    options:
      labels:
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/component: server
    literals: []

images:
  - name: minecraft-server
    newName: quay.io/crafthippie/boergers
    newTag: 3.0.30@sha256:30222574ddbd2f366bf72b8548ee453c1dddb13820d006317a30cd3b47651b06

...
