---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: minecraft-server
    options:
      labels:
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/component: server
    literals:
      - MINECRAFT_MOTD=Boergers by Webhippie

secretGenerator:
  - name: minecraft-server
    options:
      labels:
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/component: server
    literals: []

images:
  - name: minecraft-server
    newName: quay.io/crafthippie/boergers
    newTag: 3.0.44@sha256:a35463e770219c46028d606a3017d2fbe8983cdb821e382147a6495c622fdf76

...
